const express = require("express");
const http = require("http");
const https = require("https");
const { Server } = require("socket.io");
const path = require("path");

const app = express();
const server = http.createServer(app);
const io = new Server(server, {
	cors: {
		origin: "*",
		methods: ["GET", "POST"],
	},
});

app.use(express.static(path.join(__dirname, "public")));

const BIG_WORD_BANKS = {
	vi_dau: {
		easy: [
			"ngày",
			"đêm",
			"mưa",
			"nắng",
			"gió",
			"mây",
			"sông",
			"núi",
			"biển",
			"rừng",
			"trời",
			"đất",
			"lửa",
			"nước",
			"cây",
			"hoa",
			"lá",
			"cỏ",
			"chim",
			"cá",
			"nhà",
			"xe",
			"cơm",
			"áo",
			"tiền",
			"sách",
			"bút",
			"bàn",
			"ghế",
			"đèn",
			"tay",
			"chân",
			"mắt",
			"mũi",
			"tai",
			"miệng",
			"tóc",
			"răng",
			"mặt",
			"lưng",
			"anh",
			"em",
			"ông",
			"bà",
			"cha",
			"mẹ",
			"con",
			"chú",
			"bác",
			"cô",
			"thầy",
			"bạn",
			"người",
			"bé",
			"trẻ",
			"già",
			"nam",
			"nữ",
			"tôi",
			"ta",
			"mình",
			"bạn",
			"họ",
			"ai",
			"gì",
			"đâu",
			"đây",
			"đó",
			"này",
			"kia",
			"sáng",
			"trưa",
			"chiều",
			"tối",
			"hôm",
			"mai",
			"nay",
			"sớm",
			"muộn",
			"lúc",
			"giờ",
			"năm",
			"tháng",
			"tuần",
			"phút",
			"mùa",
			"xuân",
			"hè",
			"thu",
			"đông",
			"một",
			"hai",
			"ba",
			"bốn",
			"năm",
			"sáu",
			"bảy",
			"tám",
			"chín",
			"mười",
			"lớn",
			"nhỏ",
			"cao",
			"thấp",
			"dài",
			"ngắn",
			"to",
			"bé",
			"mới",
			"cũ",
			"tốt",
			"xấu",
			"đẹp",
			"hay",
			"dở",
			"nhanh",
			"chậm",
			"đúng",
			"sai",
			"dễ",
			"khó",
			"vui",
			"buồn",
			"yêu",
			"ghét",
			"thích",
			"sợ",
			"lo",
			"tin",
			"nhớ",
			"quên",
			"cười",
			"khóc",
			"nói",
			"nghe",
			"đọc",
			"viết",
			"xem",
			"ăn",
			"uống",
			"ngủ",
			"đi",
			"đến",
			"về",
			"ra",
			"vào",
			"lên",
			"xuống",
			"qua",
			"lại",
			"chạy",
			"đi",
			"đứng",
			"ngồi",
			"nằm",
			"bay",
			"bơi",
			"nhảy",
			"đánh",
			"đá",
			"mở",
			"đóng",
			"bật",
			"tắt",
			"đưa",
			"nhận",
			"cho",
			"lấy",
			"giữ",
			"mất",
			"tìm",
			"gặp",
			"gọi",
			"hỏi",
			"trả",
			"mua",
			"bán",
			"dùng",
			"làm",
			"học",
			"dạy",
			"làm",
			"sống",
			"chết",
			"sinh",
			"giúp",
			"cần",
			"muốn",
			"có",
			"không",
			"rất",
			"cũng",
			"đã",
			"đang",
			"sẽ",
			"vẫn",
			"chỉ",
			"còn",
			"được",
			"bị",
			"và",
			"hay",
			"hoặc",
			"nhưng",
			"vì",
			"nên",
			"nếu",
			"khi",
			"mà",
			"để",
			"với",
			"cho",
			"từ",
			"theo",
			"trên",
			"dưới",
			"trong",
			"ngoài",
			"trước",
			"sau",
			"bên",
			"giữa",
			"gần",
			"xa",
			"cùng",
			"khác",
			"mỗi",
			"mọi",
			"nhiều",
			"ít",
			"đủ",
			"thiếu",
			"hết",
			"thêm",
			"bớt",
			"đầu",
			"cuối",
			"giữa",
			"trái",
			"phải",
			"trong",
			"ngoài",
			"sau",
			"trước",
			"bóng",
			"hình",
			"màu",
			"âm",
			"ánh",
			"sáng",
			"đường",
			"phố",
			"làng",
			"chợ",
			"trường",
			"lớp",
			"phòng",
			"cửa",
			"tường",
			"sân",
			"vườn",
			"ruộng",
			"đồng",
			"bãi",
			"bờ",
			"cầu",
			"sách",
			"vở",
			"giấy",
			"mực",
			"kim",
			"đồng",
			"vàng",
			"bạc",
			"đá",
			"gỗ",
			"sắt",
			"vải",
			"da",
			"len",
			"bát",
			"đĩa",
			"cốc",
			"ly",
			"nồi",
			"chén",
			"dao",
			"kéo",
			"muỗng",
			"thìa",
			"bánh",
			"kẹo",
			"đường",
			"muối",
			"cá",
			"thịt",
			"trứng",
			"rau",
			"quả",
			"gạo",
			"bếp",
			"nồi",
			"xoong",
			"chảo",
			"bếp",
			"cơm",
			"cháo",
			"canh",
			"súp",
			"mì",
			"phở",
			"bún",
			"bánh",
			"sữa",
			"trà",
			"cà",
			"nước",
			"mật",
			"mía",
			"dừa",
			"cam",
			"chanh",
			"xoài",
			"ổi",
			"mít",
			"na",
			"lê",
			"đào",
			"mận",
			"dưa",
			"bí",
			"đậu",
			"ngô",
			"khoai",
			"sắn",
			"lạc",
			"vừng",
			"mè",
			"tiêu",
			"tỏi",
			"gừng",
			"ớt",
			"hành",
			"tôm",
			"cua",
			"ốc",
			"nghêu",
			"sò",
			"lươn",
			"ếch",
			"gà",
			"vịt",
			"heo",
			"bò",
			"dê",
			"ngựa",
			"trâu",
			"voi",
			"hổ",
			"sư tử",
			"gấu",
			"khỉ",
			"nai",
			"hươu",
			"cáo",
			"sói",
			"mèo",
			"thỏ",
			"chuột",
			"rắn",
			"rùa",
			"ếch",
			"ong",
			"kiến",
			"muỗi",
			"ruồi",
			"bướm",
			"sâu",
			"nhện",
			"dế",
			"đỏ",
			"xanh",
			"vàng",
			"trắng",
			"đen",
			"tím",
			"hồng",
			"nâu",
			"cam",
			"xám",
			"tròn",
			"vuông",
			"thẳng",
			"cong",
			"mềm",
			"cứng",
			"nóng",
			"lạnh",
			"ấm",
			"mát",
		],
		hard: [
			"khoảnh",
			"nghiêng",
			"khuếch",
			"khuỵu",
			"ngoéo",
			"thuở",
			"ngoằn",
			"ngoèo",
			"nghiến",
			"nguyện",
			"truyền",
			"khuyến",
			"chuyện",
			"quyển",
			"quỷ",
			"nghễu",
			"nghiễu",
			"soạn",
			"duyệt",
			"chuộng",
			"hoảng",
			"khoảng",
			"nghèo",
			"xoắn",
			"ngoắc",
			"khoác",
			"hoắt",
			"hoẵng",
			"thuần",
			"khuần",
			"ngoài",
			"quệt",
			"nghiêm",
			"nghiệm",
			"nghiệp",
			"nghiêng",
			"nguyễn",
			"quyết",
			"quyền",
			"quýnh",
			"quỳnh",
			"quyến",
			"quyện",
			"uyển",
			"uyển",
			"uyết",
			"huyễn",
			"huyền",
			"huyện",
			"chuyển",
			"chuyến",
			"chuyện",
			"chuyễn",
			"tuyển",
			"tuyến",
			"tuyệt",
			"tuyên",
			"duyên",
			"duyệt",
			"khuyết",
			"khuyến",
			"khuyên",
			"khuyển",
			"khuya",
			"khuây",
			"khuất",
			"khuẩn",
			"khuếch",
			"khuôn",
			"nguệch",
			"nguẩy",
			"nguẩy",
			"nguyện",
			"nguyệt",
			"nguyền",
			"nguyền",
			"nghịch",
			"nghiệt",
			"nghiễm",
			"nghĩa",
			"nghễnh",
			"nghệch",
			"nghênh",
			"nghiêm",
			"nghiễm",
			"nguyễn",
			"ngoảnh",
			"ngoặt",
			"ngoằn",
			"ngoẵng",
			"ngoẹo",
			"ngoét",
			"xoẹt",
			"xoắn",
			"xoạc",
			"xoạch",
			"quạnh",
			"quẫy",
			"quệt",
			"khuỷu",
			"khuất",
			"khuynh",
			"khuấy",
			"khuya",
			"khoắng",
			"khoảnh",
			"khoẻn",
			"khuyến",
			"khuyết",
			"khuyển",
			"khuyếch",
			"nghiêng",
			"nghiễm",
			"nghiến",
			"nghễnh",
			"nghệch",
			"nghênh",
			"nguyện",
			"nguyệt",
			"nguyền",
			"nguyền",
			"nguệch",
			"nguẩy",
			"ngoảnh",
			"ngoặt",
			"ngoằn",
			"ngoẵng",
			"ngoẹo",
			"ngoét",
			"xoẹt",
			"xoạc",
			"xoạch",
			"xoắn",
			"quạnh",
			"quẫy",
			"quệt",
			"quyến",
			"quyện",
			"quyền",
			"quyết",
			"quỳnh",
			"huyễn",
			"huyện",
			"uyển",
			"tuyển",
			"tuyến",
			"tuyệt",
			"duyên",
			"khuyết",
		],
	},
	vi_nodau: {
		easy: [
			"ngay",
			"dem",
			"mua",
			"nang",
			"gio",
			"may",
			"song",
			"nui",
			"bien",
			"rung",
			"troi",
			"dat",
			"lua",
			"nuoc",
			"cay",
			"hoa",
			"la",
			"co",
			"chim",
			"ca",
			"nha",
			"xe",
			"com",
			"ao",
			"tien",
			"sach",
			"but",
			"ban",
			"ghe",
			"den",
			"tay",
			"chan",
			"mat",
			"mui",
			"tai",
			"mieng",
			"toc",
			"rang",
			"mat",
			"lung",
			"anh",
			"em",
			"ong",
			"ba",
			"cha",
			"me",
			"con",
			"chu",
			"bac",
			"co",
			"thay",
			"ban",
			"nguoi",
			"be",
			"tre",
			"gia",
			"nam",
			"nu",
			"toi",
			"ta",
			"minh",
			"ban",
			"ho",
			"ai",
			"gi",
			"dau",
			"day",
			"do",
			"nay",
			"kia",
			"sang",
			"trua",
			"chieu",
			"toi",
			"hom",
			"mai",
			"nay",
			"som",
			"muon",
			"luc",
			"gio",
			"nam",
			"thang",
			"tuan",
			"phut",
			"mua",
			"xuan",
			"he",
			"thu",
			"dong",
			"mot",
			"hai",
			"ba",
			"bon",
			"nam",
			"sau",
			"bay",
			"tam",
			"chin",
			"muoi",
			"lon",
			"nho",
			"cao",
			"thap",
			"dai",
			"ngan",
			"to",
			"be",
			"moi",
			"cu",
			"tot",
			"xau",
			"dep",
			"hay",
			"do",
			"nhanh",
			"cham",
			"dung",
			"sai",
			"de",
			"kho",
			"vui",
			"buon",
			"yeu",
			"ghet",
			"thich",
			"so",
			"lo",
			"tin",
			"nho",
			"quen",
			"cuoi",
			"khoc",
			"noi",
			"nghe",
			"doc",
			"viet",
			"xem",
			"an",
			"uong",
			"ngu",
			"di",
			"den",
			"ve",
			"ra",
			"vao",
			"len",
			"xuong",
			"qua",
			"lai",
			"chay",
			"di",
			"dung",
			"ngoi",
			"nam",
			"bay",
			"boi",
			"nhay",
			"danh",
			"da",
			"mo",
			"dong",
			"bat",
			"tat",
			"dua",
			"nhan",
			"cho",
			"lay",
			"giu",
			"mat",
			"tim",
			"gap",
			"goi",
			"hoi",
			"tra",
			"mua",
			"ban",
			"dung",
			"lam",
			"hoc",
			"day",
			"lam",
			"song",
			"chet",
			"sinh",
			"giup",
			"can",
			"muon",
			"co",
			"khong",
			"rat",
			"cung",
			"da",
			"dang",
			"se",
			"van",
			"chi",
			"con",
			"duoc",
			"bi",
			"va",
			"hay",
			"hoac",
			"nhung",
			"vi",
			"nen",
			"neu",
			"khi",
			"ma",
			"de",
			"voi",
			"cho",
			"tu",
			"theo",
			"tren",
			"duoi",
			"trong",
			"ngoai",
			"truoc",
			"sau",
			"ben",
			"giua",
			"gan",
			"xa",
			"cung",
			"khac",
			"moi",
			"moi",
			"nhieu",
			"it",
			"du",
			"thieu",
			"het",
			"them",
			"bot",
			"dau",
			"cuoi",
			"giua",
			"trai",
			"phai",
			"trong",
			"ngoai",
			"sau",
			"truoc",
			"bong",
			"hinh",
			"mau",
			"am",
			"anh",
			"sang",
			"duong",
			"pho",
			"lang",
			"cho",
			"truong",
			"lop",
			"phong",
			"cua",
			"tuong",
			"san",
			"vuon",
			"ruong",
			"dong",
			"bai",
			"bo",
			"cau",
			"sach",
			"vo",
			"giay",
			"muc",
			"kim",
			"dong",
			"vang",
			"bac",
			"da",
			"go",
			"sat",
			"vai",
			"da",
			"len",
			"bat",
			"dia",
			"coc",
			"ly",
			"noi",
			"chen",
			"dao",
			"keo",
			"muong",
			"thia",
			"banh",
			"keo",
			"duong",
			"muoi",
			"ca",
			"thit",
			"trung",
			"rau",
			"qua",
			"gao",
			"bep",
			"noi",
			"xoong",
			"chao",
			"bep",
			"com",
			"chao",
			"canh",
			"sup",
			"mi",
			"pho",
			"bun",
			"banh",
			"sua",
			"tra",
			"ca",
			"nuoc",
			"mat",
			"mia",
			"dua",
			"cam",
			"chanh",
			"xoai",
			"oi",
			"mit",
			"na",
			"le",
			"dao",
			"man",
			"dua",
			"bi",
			"dau",
			"ngo",
			"khoai",
			"san",
			"lac",
			"vung",
			"me",
			"tieu",
			"toi",
			"gung",
			"ot",
			"hanh",
			"tom",
			"cua",
			"oc",
			"ngheu",
			"so",
			"luon",
			"ech",
			"ga",
			"vit",
			"heo",
			"bo",
			"de",
			"ngua",
			"trau",
			"voi",
			"ho",
			"su tu",
			"gau",
			"khi",
			"nai",
			"huou",
			"cao",
			"soi",
			"meo",
			"tho",
			"chuot",
			"ran",
			"rua",
			"ech",
			"ong",
			"kien",
			"muoi",
			"ruoi",
			"buom",
			"sau",
			"nhen",
			"de",
			"do",
			"xanh",
			"vang",
			"trang",
			"den",
			"tim",
			"hong",
			"nau",
			"cam",
			"xam",
			"tron",
			"vuong",
			"thang",
			"cong",
			"mem",
			"cung",
			"nong",
			"lanh",
			"am",
			"mat",
		],
		hard: [
			"khoanh",
			"nghieng",
			"khuech",
			"khuyu",
			"ngoeo",
			"thuo",
			"ngoan",
			"ngheo",
			"nghien",
			"nguyen",
			"truyen",
			"khuyen",
			"chuyen",
			"quyen",
			"quy",
			"ngheu",
			"nghieu",
			"soan",
			"duyet",
			"chuong",
			"hoang",
			"khoang",
			"ngheo",
			"xoan",
			"ngoac",
			"khoac",
			"hoat",
			"hoang",
			"thuan",
			"khuan",
			"ngoai",
			"quet",
			"nghiem",
			"nghiem",
			"nghiep",
			"nghieng",
			"nguyen",
			"quyet",
			"quyen",
			"quynh",
			"quynh",
			"quyen",
			"quyen",
			"uyen",
			"uyen",
			"uyet",
			"huyen",
			"huyen",
			"huyen",
			"chuyen",
			"chuyen",
			"chuyen",
			"chuyen",
			"tuyen",
			"tuyen",
			"tuyet",
			"tuyen",
			"duyen",
			"duyet",
			"khuyet",
			"khuyen",
			"khuyen",
			"khuyen",
			"khuya",
			"khuay",
			"khuat",
			"khuan",
			"khuech",
			"khuon",
			"nguech",
			"nguy",
			"nguy",
			"nguyen",
			"nguyet",
			"nguyen",
			"nguyen",
			"nghich",
			"nghiet",
			"nghiem",
			"nghia",
			"nghenh",
			"nghech",
			"nghenh",
			"nghiem",
			"nghiem",
			"nguyen",
			"ngoanh",
			"ngoat",
			"ngoan",
			"ngoang",
			"ngoeo",
			"ngoet",
			"xoet",
			"xoan",
			"xoac",
			"xoach",
			"quanh",
			"quay",
			"quet",
			"khuyu",
			"khuat",
			"khuynh",
			"khuay",
			"khuya",
			"khoang",
			"khoanh",
			"khoen",
			"khuyen",
			"khuyet",
			"khuyen",
			"khuech",
			"nghieng",
			"nghiem",
			"nghien",
			"nghenh",
			"nghech",
			"nghenh",
			"nguyen",
			"nguyet",
			"nguyen",
			"nguyen",
			"nguech",
			"nguay",
			"ngoanh",
			"ngoat",
			"ngoan",
			"ngoang",
			"ngoeo",
			"ngoet",
			"xoet",
			"xoac",
			"xoach",
			"xoan",
			"quanh",
			"quay",
			"quet",
			"quyen",
			"quyen",
			"quyen",
			"quyet",
			"quynh",
			"huyen",
			"huyen",
			"uyen",
			"tuyen",
			"tuyen",
			"tuyet",
			"duyen",
			"khuyet",
		],
	},
	en: {
		easy: [
			"cat",
			"dog",
			"sun",
			"moon",
			"star",
			"tree",
			"book",
			"pen",
			"desk",
			"fish",
			"fast",
			"good",
			"apple",
			"orange",
			"grape",
			"peach",
			"pear",
			"lemon",
			"melon",
			"berry",
			"bread",
			"rice",
			"cake",
			"soup",
			"milk",
			"water",
			"juice",
			"coffee",
			"tea",
			"sugar",
			"salt",
			"egg",
			"meat",
			"beef",
			"pork",
			"fish",
			"chicken",
			"duck",
			"horse",
			"sheep",
			"goat",
			"mouse",
			"house",
			"home",
			"room",
			"door",
			"wall",
			"floor",
			"roof",
			"bed",
			"chair",
			"table",
			"school",
			"class",
			"teacher",
			"student",
			"friend",
			"family",
			"mother",
			"father",
			"sister",
			"brother",
			"baby",
			"child",
			"boy",
			"girl",
			"man",
			"woman",
			"king",
			"queen",
			"name",
			"face",
			"hand",
			"head",
			"hair",
			"eye",
			"ear",
			"nose",
			"mouth",
			"foot",
			"leg",
			"arm",
			"car",
			"bus",
			"train",
			"boat",
			"road",
			"street",
			"park",
			"shop",
			"store",
			"farm",
			"red",
			"blue",
			"green",
			"white",
			"black",
			"brown",
			"pink",
			"gray",
			"round",
			"square",
			"big",
			"small",
			"long",
			"short",
			"high",
			"low",
			"hot",
			"cold",
			"warm",
			"cool",
		],
		hard: [
			"rhythm",
			"queue",
			"knapsack",
			"quizzical",
			"puzzling",
			"knowledge",
			"strength",
			"synergy",
			"awkward",
			"beautiful",
			"bizarre",
			"brilliant",
			"cautious",
			"curious",
			"dangerous",
			"delicate",
			"difficult",
			"efficient",
			"enormous",
			"excellent",
			"fascinating",
			"fortunate",
			"generous",
			"gorgeous",
			"grateful",
			"harmonious",
			"impressive",
			"incredible",
			"independent",
			"intelligent",
			"mysterious",
			"necessary",
			"obvious",
			"optimistic",
			"particular",
			"powerful",
			"precious",
			"previous",
			"reasonable",
			"remarkable",
			"significant",
			"spectacular",
			"successful",
			"surprising",
			"technical",
			"thoughtful",
			"traditional",
			"unusual",
			"valuable",
			"wonderful",
			"adventure",
			"challenge",
			"experience",
			"knowledge",
			"language",
			"question",
			"strength",
			"throughout",
		],
	},
};

const runnerIcons = ["🐶", "🐭", "🐷", "🐱", "🐨", "🐯", "🐺", "🐰", "🦝", "🐵"];

function generateWords(lang, count = 100) {
	if (lang === "numpad") {
		const zipList = [];
		for (let i = 0; i < 500; i++) {
			zipList.push(Math.floor(10000 + Math.random() * 90000).toString());
		}
		return zipList;
	}

	const bank = BIG_WORD_BANKS[lang] || BIG_WORD_BANKS.vi_dau;
	const result = [];
	for (let i = 0; i < count; i++) {
		const isHard = Math.random() < 0.3;
		const pool = isHard ? bank.hard : bank.easy;
		const randomWord = pool[Math.floor(Math.random() * pool.length)];
		result.push(randomWord);
	}
	return result;
}

const rooms = { en: [], vi_nodau: [], vi_dau: [], numpad: [] };
let totalOnlineUsers = 0;

function getOrCreateRoom(lang) {
	let roomList = rooms[lang] || rooms.vi_dau;
	let room = roomList.find((r) => r.state === "waiting" && r.players.length < 10);

	if (!room) {
		room = {
			id: "room_" + lang + "_" + Date.now() + "_" + Math.floor(Math.random() * 1000),
			lang: lang,
			state: "waiting",
			players: [],
			words: generateWords(lang),
			matchInterval: null,
			startTime: null,
			finishedCount: 0,
		};
		roomList.push(room);
	}
	return room;
}

function checkMatchCompletion(room) {
	const activeOrFinished = room.players.filter(
		(p) => p.isFinished || p.isSurrendered || p.isDisconnected,
	);
	if (activeOrFinished.length >= room.players.length) {
		finishMatch(room);
	}
}

io.on("connection", (socket) => {
	totalOnlineUsers++;
	io.emit("update_online_count", totalOnlineUsers);

	let currentRoom = null;
	let player = null;

	socket.on("join_lobby", ({ username, language, selectedIcon }) => {
		const selectedLang = language || "vi_dau";
		currentRoom = getOrCreateRoom(selectedLang);

		// Chọn icon mặc định ngẫu nhiên nếu không truyền selectedIcon
		const defaultIcon = selectedIcon || runnerIcons[Math.floor(Math.random() * runnerIcons.length)];

		player = {
			id: socket.id,
			username: username || "TayĐua_" + Math.floor(1000 + Math.random() * 9000),
			icon: defaultIcon,
			progress: 0,
			wpm: 0,
			correctChars: 0,
			errors: 0,
			isFinished: false,
			isSurrendered: false,
			isDisconnected: false,
		};

		currentRoom.players.push(player);
		socket.join(currentRoom.id);

		io.to(currentRoom.id).emit("update_lobby", {
			players: currentRoom.players,
			lang: currentRoom.lang,
		});
	});

	socket.on("select_icon", ({ icon }) => {
		if (player && currentRoom && currentRoom.state === "waiting") {
			// Kiểm tra xem icon này đã được người khác chọn chưa
			const isTaken = currentRoom.players.some((p) => p.id !== player.id && p.icon === icon);
			if (!isTaken) {
				player.icon = icon;
				io.to(currentRoom.id).emit("update_lobby", {
					players: currentRoom.players,
					lang: currentRoom.lang,
				});
			}
		}
	});

	socket.on("force_start_game", () => {
		if (currentRoom && currentRoom.state === "waiting") {
			currentRoom.state = "racing";
			io.to(currentRoom.id).emit("game_start", {
				words: currentRoom.words,
				players: currentRoom.players,
				countdown: 3,
			});
		}
	});

	socket.on("update_username", ({ username }) => {
		if (player) {
			player.username = username;
			if (currentRoom) {
				io.to(currentRoom.id).emit("update_lobby", {
					players: currentRoom.players,
				});
			}
		}
	});

	socket.on("update_progress", (data) => {
		if (
			!currentRoom ||
			currentRoom.state !== "racing" ||
			!player ||
			player.isSurrendered ||
			player.isDisconnected
		)
			return;

		player.progress = data.progress || 0;
		player.wpm = data.wpm || 0;
		player.correctChars = data.correctChars || 0;
		player.errors = data.errors || 0;

		if (!currentRoom.startTime) {
			currentRoom.startTime = Date.now();
			io.to(currentRoom.id).emit("race_start_timer");

			const DURATION_MS = currentRoom.lang === "numpad" ? 90 * 1000 : 5 * 60 * 1000;

			currentRoom.matchInterval = setTimeout(() => {
				finishMatch(currentRoom);
			}, DURATION_MS);
		}

		io.to(currentRoom.id).emit("race_update", currentRoom.players);
	});

	socket.on("player_finished", (data) => {
		if (
			!currentRoom ||
			!player ||
			player.isFinished ||
			player.isSurrendered ||
			player.isDisconnected
		)
			return;

		player.isFinished = true;
		player.wpm = data.wpm;
		player.correctChars = data.correctChars;
		player.errors = data.errors;
		player.progress = 100;

		currentRoom.finishedCount++;
		checkMatchCompletion(currentRoom);
	});

	socket.on("surrender", () => {
		if (
			!currentRoom ||
			!player ||
			player.isFinished ||
			player.isSurrendered ||
			player.isDisconnected
		)
			return;

		player.isSurrendered = true;
		player.wpm = 0;

		io.to(currentRoom.id).emit("race_update", currentRoom.players);
		checkMatchCompletion(currentRoom);
	});

	socket.on("send_global_chat", ({ message, username }) => {
		if (!message || !message.trim()) return;

		const senderName = player && player.username ? player.username : username || "Vô danh";

		io.emit("receive_global_chat", {
			username: senderName,
			message: message.trim(),
			timestamp: Date.now(),
		});
	});

	socket.on("send_in_game_chat", ({ message }) => {
		if (currentRoom && player && message) {
			io.to(currentRoom.id).emit("receive_in_game_chat", {
				username: player.username,
				message: message.trim(),
			});
		}
	});

	socket.on("disconnect", () => {
		totalOnlineUsers = Math.max(0, totalOnlineUsers - 1);
		io.emit("update_online_count", totalOnlineUsers);

		if (currentRoom && player) {
			if (currentRoom.state === "waiting") {
				currentRoom.players = currentRoom.players.filter((p) => p.id !== socket.id);

				if (currentRoom.players.length === 0) {
					if (currentRoom.matchInterval) clearTimeout(currentRoom.matchInterval);
					if (rooms[currentRoom.lang]) {
						rooms[currentRoom.lang] = rooms[currentRoom.lang].filter(
							(r) => r.id !== currentRoom.id,
						);
					}
				} else {
					io.to(currentRoom.id).emit("update_lobby", { players: currentRoom.players });
				}
			} else if (currentRoom.state === "racing") {
				player.isDisconnected = true;
				player.wpm = 0;
				io.to(currentRoom.id).emit("race_update", currentRoom.players);
				checkMatchCompletion(currentRoom);
			}
		}
	});
});

function finishMatch(room) {
	if (room.state === "finished") return;
	room.state = "finished";
	if (room.matchInterval) clearTimeout(room.matchInterval);

	const leaderboard = [...room.players].sort((a, b) => {
		if (a.isSurrendered || a.isDisconnected) return 1;
		if (b.isSurrendered || b.isDisconnected) return -1;

		if (b.wpm !== a.wpm) {
			return b.wpm - a.wpm;
		}
		return a.errors - b.errors;
	});
	io.to(room.id).emit("game_over", leaderboard);
}

const PORT = process.env.PORT || 3000;
server.listen(PORT, () => console.log(`Server đang chạy trên port ${PORT}`));
