const express = require("express");
const http = require("http");
const https = require("https");
const { Server } = require("socket.io");
const path = require("path");

const app = express();
const server = http.createServer(app);
const io = new Server(server, {
	cors: {
		origin: "*",
		methods: ["GET", "POST"],
	},
});

app.use(express.static(path.join(__dirname, "public")));

// =========================================================================
// DANH SÁCH TỪ VỰNG (70% DỄ - 30% KHÓ)
// =========================================================================
const BIG_WORD_BANKS = {
	vi_dau: {
		// 300 từ dễ
		easy: [
			"ngày",
			"đêm",
			"mưa",
			"nắng",
			"gió",
			"mây",
			"sông",
			"núi",
			"biển",
			"rừng",
			"trời",
			"đất",
			"lửa",
			"nước",
			"cây",
			"hoa",
			"lá",
			"cỏ",
			"chim",
			"cá",
			"nhà",
			"xe",
			"cơm",
			"áo",
			"tiền",
			"sách",
			"bút",
			"bàn",
			"ghế",
			"đèn",
			"tay",
			"chân",
			"mắt",
			"mũi",
			"tai",
			"miệng",
			"tóc",
			"răng",
			"mặt",
			"lưng",
			"anh",
			"em",
			"ông",
			"bà",
			"cha",
			"mẹ",
			"con",
			"chú",
			"bác",
			"cô",
			"thầy",
			"bạn",
			"người",
			"bé",
			"trẻ",
			"già",
			"nam",
			"nữ",
			"tôi",
			"ta",
			"mình",
			"bạn",
			"họ",
			"ai",
			"gì",
			"đâu",
			"đây",
			"đó",
			"này",
			"kia",
			"sáng",
			"trưa",
			"chiều",
			"tối",
			"hôm",
			"mai",
			"nay",
			"sớm",
			"muộn",
			"lúc",
			"giờ",
			"năm",
			"tháng",
			"tuần",
			"phút",
			"mùa",
			"xuân",
			"hè",
			"thu",
			"đông",
			"một",
			"hai",
			"ba",
			"bốn",
			"năm",
			"sáu",
			"bảy",
			"tám",
			"chín",
			"mười",
			"lớn",
			"nhỏ",
			"cao",
			"thấp",
			"dài",
			"ngắn",
			"to",
			"bé",
			"mới",
			"cũ",
			"tốt",
			"xấu",
			"đẹp",
			"hay",
			"dở",
			"nhanh",
			"chậm",
			"đúng",
			"sai",
			"dễ",
			"khó",
			"vui",
			"buồn",
			"yêu",
			"ghét",
			"thích",
			"sợ",
			"lo",
			"tin",
			"nhớ",
			"quên",
			"cười",
			"khóc",
			"nói",
			"nghe",
			"đọc",
			"viết",
			"xem",
			"ăn",
			"uống",
			"ngủ",
			"đi",
			"đến",
			"về",
			"ra",
			"vào",
			"lên",
			"xuống",
			"qua",
			"lại",
			"chạy",
			"đi",
			"đứng",
			"ngồi",
			"nằm",
			"bay",
			"bơi",
			"nhảy",
			"đánh",
			"đá",
			"mở",
			"đóng",
			"bật",
			"tắt",
			"đưa",
			"nhận",
			"cho",
			"lấy",
			"giữ",
			"mất",
			"tìm",
			"gặp",
			"gọi",
			"hỏi",
			"trả",
			"mua",
			"bán",
			"dùng",
			"làm",
			"học",
			"dạy",
			"làm",
			"sống",
			"chết",
			"sinh",
			"giúp",
			"cần",
			"muốn",
			"có",
			"không",
			"rất",
			"cũng",
			"đã",
			"đang",
			"sẽ",
			"vẫn",
			"chỉ",
			"còn",
			"được",
			"bị",
			"và",
			"hay",
			"hoặc",
			"nhưng",
			"vì",
			"nên",
			"nếu",
			"khi",
			"mà",
			"để",
			"với",
			"cho",
			"từ",
			"theo",
			"trên",
			"dưới",
			"trong",
			"ngoài",
			"trước",
			"sau",
			"bên",
			"giữa",
			"gần",
			"xa",
			"cùng",
			"khác",
			"mỗi",
			"mọi",
			"nhiều",
			"ít",
			"đủ",
			"thiếu",
			"hết",
			"thêm",
			"bớt",
			"đầu",
			"cuối",
			"giữa",
			"trái",
			"phải",
			"trong",
			"ngoài",
			"sau",
			"trước",
			"bóng",
			"hình",
			"màu",
			"âm",
			"ánh",
			"sáng",
			"đường",
			"phố",
			"làng",
			"chợ",
			"trường",
			"lớp",
			"phòng",
			"cửa",
			"tường",
			"sân",
			"vườn",
			"ruộng",
			"đồng",
			"bãi",
			"bờ",
			"cầu",
			"sách",
			"vở",
			"giấy",
			"mực",
			"kim",
			"đồng",
			"vàng",
			"bạc",
			"đá",
			"gỗ",
			"sắt",
			"vải",
			"da",
			"len",
			"bát",
			"đĩa",
			"cốc",
			"ly",
			"nồi",
			"chén",
			"dao",
			"kéo",
			"muỗng",
			"thìa",
			"bánh",
			"kẹo",
			"đường",
			"muối",
			"cá",
			"thịt",
			"trứng",
			"rau",
			"quả",
			"gạo",
		],

		// 100 từ khó
		hard: [
			"khoảnh",
			"nghiêng",
			"khuếch",
			"khuỵu",
			"ngoéo",
			"thuở",
			"ngoằn",
			"ngoèo",
			"nghiến",
			"nguyện",
			"truyền",
			"khuyến",
			"chuyện",
			"quyển",
			"quỷ",
			"nghễu",
			"nghiễu",
			"soạn",
			"duyệt",
			"chuộng",
			"hoảng",
			"khoảng",
			"nghèo",
			"xoắn",
			"ngoắc",
			"khoác",
			"hoắt",
			"hoẵng",
			"thuần",
			"khuần",
			"ngoài",
			"quệt",
			"nghiêm",
			"nghiệm",
			"nghiệp",
			"nghiêng",
			"nguyễn",
			"quyết",
			"quyền",
			"quýnh",
			"quỳnh",
			"quyến",
			"quyện",
			"uyển",
			"uyển",
			"uyết",
			"huyễn",
			"huyền",
			"huyện",
			"chuyển",
			"chuyến",
			"chuyện",
			"chuyễn",
			"tuyển",
			"tuyến",
			"tuyệt",
			"tuyên",
			"duyên",
			"duyệt",
			"duy trì",
			"khuyết",
			"khuyến",
			"khuyên",
			"khuyển",
			"khuya",
			"khuây",
			"khuất",
			"khuẩn",
			"khuếch",
			"khuôn",
			"nguệch",
			"nguẩy",
			"nguẩy",
			"nguyện",
			"nguyệt",
			"nguyền",
			"nguyền",
			"nghịch",
			"nghiệt",
			"nghiễm",
			"nghĩa",
			"nghễnh",
			"nghệch",
			"nghênh",
			"nghiêm",
			"nghiễm",
			"nguyễn",
			"ngoảnh",
			"ngoặt",
			"ngoằn",
			"ngoẵng",
			"ngoẹo",
			"ngoét",
			"xoẹt",
			"xoắn",
			"xoạc",
			"xoạch",
			"quạnh",
			"quẫy",
			"quệt",
		],
	},

	vi_nodau: {
		// 300 từ dễ — đồng bộ 1:1 với vi_dau.easy
		easy: [
			"ngay",
			"dem",
			"mua",
			"nang",
			"gio",
			"may",
			"song",
			"nui",
			"bien",
			"rung",
			"troi",
			"dat",
			"lua",
			"nuoc",
			"cay",
			"hoa",
			"la",
			"co",
			"chim",
			"ca",
			"nha",
			"xe",
			"com",
			"ao",
			"tien",
			"sach",
			"but",
			"ban",
			"ghe",
			"den",
			"tay",
			"chan",
			"mat",
			"mui",
			"tai",
			"mieng",
			"toc",
			"rang",
			"mat",
			"lung",
			"anh",
			"em",
			"ong",
			"ba",
			"cha",
			"me",
			"con",
			"chu",
			"bac",
			"co",
			"thay",
			"ban",
			"nguoi",
			"be",
			"tre",
			"gia",
			"nam",
			"nu",
			"toi",
			"ta",
			"minh",
			"ban",
			"ho",
			"ai",
			"gi",
			"dau",
			"day",
			"do",
			"nay",
			"kia",
			"sang",
			"trua",
			"chieu",
			"toi",
			"hom",
			"mai",
			"nay",
			"som",
			"muon",
			"luc",
			"gio",
			"nam",
			"thang",
			"tuan",
			"phut",
			"mua",
			"xuan",
			"he",
			"thu",
			"dong",
			"mot",
			"hai",
			"ba",
			"bon",
			"nam",
			"sau",
			"bay",
			"tam",
			"chin",
			"muoi",
			"lon",
			"nho",
			"cao",
			"thap",
			"dai",
			"ngan",
			"to",
			"be",
			"moi",
			"cu",
			"tot",
			"xau",
			"dep",
			"hay",
			"do",
			"nhanh",
			"cham",
			"dung",
			"sai",
			"de",
			"kho",
			"vui",
			"buon",
			"yeu",
			"ghet",
			"thich",
			"so",
			"lo",
			"tin",
			"nho",
			"quen",
			"cuoi",
			"khoc",
			"noi",
			"nghe",
			"doc",
			"viet",
			"xem",
			"an",
			"uong",
			"ngu",
			"di",
			"den",
			"ve",
			"ra",
			"vao",
			"len",
			"xuong",
			"qua",
			"lai",
			"chay",
			"di",
			"dung",
			"ngoi",
			"nam",
			"bay",
			"boi",
			"nhay",
			"danh",
			"da",
			"mo",
			"dong",
			"bat",
			"tat",
			"dua",
			"nhan",
			"cho",
			"lay",
			"giu",
			"mat",
			"tim",
			"gap",
			"goi",
			"hoi",
			"tra",
			"mua",
			"ban",
			"dung",
			"lam",
			"hoc",
			"day",
			"lam",
			"song",
			"chet",
			"sinh",
			"giup",
			"can",
			"muon",
			"co",
			"khong",
			"rat",
			"cung",
			"da",
			"dang",
			"se",
			"van",
			"chi",
			"con",
			"duoc",
			"bi",
			"va",
			"hay",
			"hoac",
			"nhung",
			"vi",
			"nen",
			"neu",
			"khi",
			"ma",
			"de",
			"voi",
			"cho",
			"tu",
			"theo",
			"tren",
			"duoi",
			"trong",
			"ngoai",
			"truoc",
			"sau",
			"ben",
			"giua",
			"gan",
			"xa",
			"cung",
			"khac",
			"moi",
			"moi",
			"nhieu",
			"it",
			"du",
			"thieu",
			"het",
			"them",
			"bot",
			"dau",
			"cuoi",
			"giua",
			"trai",
			"phai",
			"trong",
			"ngoai",
			"sau",
			"truoc",
			"bong",
			"hinh",
			"mau",
			"am",
			"anh",
			"sang",
			"duong",
			"pho",
			"lang",
			"cho",
			"truong",
			"lop",
			"phong",
			"cua",
			"tuong",
			"san",
			"vuon",
			"ruong",
			"dong",
			"bai",
			"bo",
			"cau",
			"sach",
			"vo",
			"giay",
			"muc",
			"kim",
			"dong",
			"vang",
			"bac",
			"da",
			"go",
			"sat",
			"vai",
			"da",
			"len",
			"bat",
			"dia",
			"coc",
			"ly",
			"noi",
			"chen",
			"dao",
			"keo",
			"muong",
			"thia",
			"banh",
			"keo",
			"duong",
			"muoi",
			"ca",
			"thit",
			"trung",
			"rau",
			"qua",
			"gao",
		],

		// 100 từ khó — đồng bộ 1:1 với vi_dau.hard
		hard: [
			"khoanh",
			"nghieng",
			"khuech",
			"khuyu",
			"ngoeo",
			"thuo",
			"ngoan",
			"ngheo",
			"nghien",
			"nguyen",
			"truyen",
			"khuyen",
			"chuyen",
			"quyen",
			"quy",
			"ngheu",
			"nghieu",
			"soan",
			"duyet",
			"chuong",
			"hoang",
			"khoang",
			"ngheo",
			"xoan",
			"ngoac",
			"khoac",
			"hoat",
			"hoang",
			"thuan",
			"khuan",
			"ngoai",
			"quet",
			"nghiem",
			"nghiem",
			"nghiep",
			"nghieng",
			"nguyen",
			"quyet",
			"quyen",
			"quynh",
			"quynh",
			"quyen",
			"quyen",
			"uyen",
			"uyen",
			"uyet",
			"huyen",
			"huyen",
			"huyen",
			"chuyen",
			"chuyen",
			"chuyen",
			"chuyen",
			"tuyen",
			"tuyen",
			"tuyet",
			"tuyen",
			"duyen",
			"duyet",
			"duy tri",
			"khuyet",
			"khuyen",
			"khuyen",
			"khuyen",
			"khuya",
			"khuay",
			"khuat",
			"khuan",
			"khuech",
			"khuon",
			"nguech",
			"nguy",
			"nguy",
			"nguyen",
			"nguyet",
			"nguyen",
			"nguyen",
			"nghich",
			"nghiet",
			"nghiem",
			"nghia",
			"nghenh",
			"nghech",
			"nghenh",
			"nghiem",
			"nghiem",
			"nguyen",
			"ngoanh",
			"ngoat",
			"ngoan",
			"ngoang",
			"ngoeo",
			"ngoet",
			"xoet",
			"xoan",
			"xoac",
			"xoach",
			"quanh",
			"quay",
			"quet",
		],
	},
	en: {
		easy: [
			"cat",
			"dog",
			"sun",
			"moon",
			"star",
			"tree",
			"book",
			"pen",
			"desk",
			"fish",
			"fast",
			"good",
		],
		hard: [
			"rhythm",
			"queue",
			"knapsack",
			"quizzical",
			"puzzling",
			"knowledge",
			"strength",
			"synergy",
		],
	},
};

function generateWords(lang, count = 100) {
	const bank = BIG_WORD_BANKS[lang] || BIG_WORD_BANKS.vi_dau;
	const result = [];
	for (let i = 0; i < count; i++) {
		const isHard = Math.random() < 0.3;
		const pool = isHard ? bank.hard : bank.easy;
		const randomWord = pool[Math.floor(Math.random() * pool.length)];
		result.push(randomWord);
	}
	return result;
}

const rooms = { en: [], vi_nodau: [], vi_dau: [] };
let totalOnlineUsers = 0;

function getOrCreateRoom(lang) {
	let roomList = rooms[lang] || rooms.vi_dau;
	let room = roomList.find((r) => r.state === "waiting" && r.players.length < 10);

	if (!room) {
		room = {
			id: "room_" + lang + "_" + Date.now() + "_" + Math.floor(Math.random() * 1000),
			lang: lang,
			state: "waiting",
			players: [],
			words: generateWords(lang),
			matchInterval: null,
			finishedCount: 0,
		};
		roomList.push(room);
	}
	return room;
}

// =========================================================================
// XỬ LÝ KẾT NỐI REALTIME (SOCKET.IO)
// =========================================================================
io.on("connection", (socket) => {
	totalOnlineUsers++;
	io.emit("update_online_count", totalOnlineUsers);

	let currentRoom = null;
	let player = null;

	// 1. NGƯỜI CHƠI VÀO PHÒNG CHỜ
	socket.on("join_lobby", ({ username, language }) => {
		const selectedLang = language || "vi_dau";
		currentRoom = getOrCreateRoom(selectedLang);

		player = {
			id: socket.id,
			username: username || "TayĐua_" + Math.floor(1000 + Math.random() * 9000),
			progress: 0,
			wpm: 0,
			correctChars: 0,
			errors: 0,
			isFinished: false,
		};

		currentRoom.players.push(player);
		socket.join(currentRoom.id);

		io.to(currentRoom.id).emit("update_lobby", {
			players: currentRoom.players,
			lang: currentRoom.lang,
		});
	});

	// 2. BẤM NÚT "BẮT ĐẦU TRẬN ĐẤU NGAY"
	socket.on("force_start_game", () => {
		if (currentRoom && currentRoom.state === "waiting") {
			currentRoom.state = "racing";
			io.to(currentRoom.id).emit("game_start", {
				words: currentRoom.words,
				players: currentRoom.players,
				countdown: 3,
			});
		}
	});

	// 3. ĐỔI TÊN NGƯỜI CHƠI
	socket.on("update_username", ({ username }) => {
		if (player) {
			player.username = username;
			if (currentRoom) {
				io.to(currentRoom.id).emit("update_lobby", {
					players: currentRoom.players,
				});
			}
		}
	});

	// 4. CẬP NHẬT TIẾN ĐỘ DẠY THI ĐẤU (REALTIME RACE)
	socket.on("update_progress", (data) => {
		if (!currentRoom || currentRoom.state !== "racing" || !player) return;

		player.progress = data.progress || 0;
		player.wpm = data.wpm || 0;
		player.correctChars = data.correctChars || 0;
		player.errors = data.errors || 0;

		io.to(currentRoom.id).emit("race_update", currentRoom.players);
	});

	// 5. NGƯỜI CHƠI HOÀN THÀNH
	socket.on("player_finished", (data) => {
		if (!currentRoom || !player || player.isFinished) return;

		player.isFinished = true;
		player.wpm = data.wpm;
		player.correctChars = data.correctChars;
		player.errors = data.errors;
		player.progress = 100;

		currentRoom.finishedCount++;

		if (currentRoom.finishedCount >= currentRoom.players.length) {
			finishMatch(currentRoom);
		}
	});

	// 6. GLOBAL CHAT & IN-GAME CHAT (Xử lý toàn diện kể cả khi user chưa vào phòng chờ)
	socket.on("send_global_chat", ({ message, username }) => {
		if (!message || !message.trim()) return;

		const senderName = player && player.username ? player.username : username || "Vô danh";

		io.emit("receive_global_chat", {
			username: senderName,
			message: message.trim(),
			timestamp: Date.now(),
		});
	});

	socket.on("send_in_game_chat", ({ message }) => {
		if (currentRoom && player && message) {
			io.to(currentRoom.id).emit("receive_in_game_chat", {
				username: player.username,
				message: message.trim(),
			});
		}
	});

	// 7. XỬ LÝ NGẮT KẾT NỐI
	socket.on("disconnect", () => {
		totalOnlineUsers = Math.max(0, totalOnlineUsers - 1);
		io.emit("update_online_count", totalOnlineUsers);

		if (currentRoom && player) {
			currentRoom.players = currentRoom.players.filter((p) => p.id !== socket.id);

			if (currentRoom.players.length === 0) {
				if (rooms[currentRoom.lang]) {
					rooms[currentRoom.lang] = rooms[currentRoom.lang].filter((r) => r.id !== currentRoom.id);
				}
			} else {
				if (currentRoom.state === "waiting") {
					io.to(currentRoom.id).emit("update_lobby", { players: currentRoom.players });
				} else if (currentRoom.state === "racing") {
					io.to(currentRoom.id).emit("race_update", currentRoom.players);
				}
			}
		}
	});
});

function finishMatch(room) {
	if (room.state === "finished") return;
	room.state = "finished";

	const leaderboard = [...room.players].sort((a, b) => b.wpm - a.wpm);
	io.to(room.id).emit("game_over", leaderboard);
}

// Keep-Alive Service
const RENDER_EXTERNAL_URL = process.env.RENDER_EXTERNAL_URL;
if (RENDER_EXTERNAL_URL) {
	setInterval(
		() => {
			const protocol = RENDER_EXTERNAL_URL.startsWith("https") ? https : http;
			protocol
				.get(RENDER_EXTERNAL_URL, (res) => {
					console.log(`[Keep-Alive] Ping Server: ${res.statusCode}`);
				})
				.on("error", (err) => console.error("[Keep-Alive] Lỗi:", err.message));
		},
		10 * 60 * 1000,
	);
}

const PORT = process.env.PORT || 3000;
server.listen(PORT, () => console.log(`Server đang chạy trên port ${PORT}`));
